default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: captain_development

test:
  <<: *default
  database: captain_test

production:
  primary:
    adapter: postgresql
    database: <%= ENV['POSTGRES_DB'] %>
    host: <%= ENV['DB_HOST'] %>
    username: <%= ENV['POSTGRES_USER'] %>
    password: <%= ENV['POSTGRES_PASSWORD'] %>
