service: captest

image: dobrinov/captest

servers:
  web:
    - testove-kapitan-40bt.com

proxy:
  ssl: true
  host: testove-kapitan-40bt.com

registry:
  username: dobrinov
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  clear:
    DB_HOST: captest-db
    POSTGRES_DB: captest_production
    POSTGRES_USER: postgres
    DB_PORT: 5432

  secret:
    - RAILS_MASTER_KEY
    - POSTGRES_PASSWORD

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

volumes:
  - "captest_storage:/rails/storage"

asset_path: /rails/public/assets

builder:
  arch: arm64

accessories:
  db:
    image: postgres:17
    host: testove-kapitan-40bt.com
    port: 127.0.0.1:5432:5432
    env:
      clear:
        POSTGRES_USER: postgres
        POSTGRES_DB: captest_production
      secret:
        - POSTGRES_PASSWORD
    directories:
      - data:/var/lib/postgresql/data
    files:
      - db/structure.sql:/docker-entrypoint-initdb.d/setup.sql
